server:
  port: 8081
spring:
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
